name: VRML_APP
description: Demonstrates how to use the flutter_web_auth plugin.
publish_to: 'none'
version: 0.1.0+10
environment:
  sdk: ">=2.12.0 <3.0.0"

  
  

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^4.0.2
  http: ^0.13.4
  json_annotation: ^4.4.0 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  toggle_switch: ^1.3.0
  sliding_switch: ^1.0.0
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  date_time_format: ^2.0.1
  wheel_chooser: ^1.0.0
  flutter_material_pickers: ^3.1.2
  vertical_picker: ^0.0.1
  country_list_pick: ^1.0.1+5
  provider: ^6.0.2
  shared_preferences:
  url_launcher: ^6.0.18

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.4
  flutter_web_auth: ^0.4.0 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/vrml.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
